version: '3'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7800:7900" 
    restart : always
    environment:
      SE_VNC_NO_PASSWORD: 1
      SE_NO_VNC_PORT: 7900
      VNC_PASSWORD: secret  # Mật khẩu noVNC

  coinmarketcapture:
    container_name: coinmarketcapture
    image: coinmarketcapture:latest
    # build:
    #   context: .
    #   dockerfile: ./app/Dockerfile
    volumes:
      - ./images:/app/images
      - ./config:/etc/coinmarketcapture
    restart : always